services:
  registry:
    # Built using ko (see Makefile dev-compose target)
    # Image format: ko.local/<import-path>:<tag>
    image: ko.local/github.com/modelcontextprotocol/registry/cmd/registry:dev
    container_name: registry
    # See .env.example for more documentation
    environment:
      - MCP_REGISTRY_ENVIRONMENT=${MCP_REGISTRY_ENVIRONMENT:-test}
      - MCP_REGISTRY_SEED_FROM=${MCP_REGISTRY_SEED_FROM:-data/seed.json}
      - MCP_REGISTRY_ENABLE_REGISTRY_VALIDATION=${MCP_REGISTRY_ENABLE_REGISTRY_VALIDATION:-true}
    ports:
      - 8080:8080
    volumes:
      - ./data:/data:ro
    restart: "unless-stopped"
